######################################################################
# Automatically generated by qmake (2.01a) mié feb 21 13:36:26 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += interfaz2.h
FORMS += interfaz2.ui
SOURCES += interfaz2.cpp main.cpp
